include $(TEST)/test_common/Makefile.inc

include $(TEST)/unit/Makefile.inc
include $(TEST)/asm_test/Makefile.inc

include $(TEST)/esbmc_unit/Makefile.inc
include $(TEST)/esbmc_check/Makefile.inc
include $(TEST)/esbmc_equiv/Makefile.inc
include $(TEST)/esbmc_isa/Makefile.inc
