CORE_SRCS += $(SRC)/core/core.c
CORE_SRCS += $(SRC)/core/arch_state.c
CORE_SRCS += $(SRC)/core/instruction_decoder.c
CORE_SRCS += $(SRC)/core/execution_engine.c
CORE_SRCS += $(SRC)/core/memory_access.c
CORE_SRCS += $(SRC)/core/writeback.c
