CORE_SRCS += $(SRC)/core/core.c
CORE_SRCS += $(SRC)/core/arch_state.c
CORE_SRCS += $(SRC)/core/instruction_fetch.c
CORE_SRCS += $(SRC)/core/instruction_decode.c
CORE_SRCS += $(SRC)/core/execute.c
CORE_SRCS += $(SRC)/core/memory.c
CORE_SRCS += $(SRC)/core/writeback.c
CORE_SRCS += $(SRC)/core/forwarding_unit.c
